KeyError in line 30 of /project/jnovembre/chichun/ancient-imputation-experiment/snakemake/snakefile_downsample_bams.py:
'{id}'
  File "/project/jnovembre/chichun/ancient-imputation-experiment/snakemake/snakefile_downsample_bams.py", line 30, in <module>
  File "/home/chichun/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2139, in __getitem__
  File "/home/chichun/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2146, in _getitem_column
  File "/home/chichun/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 1842, in _get_item_cache
  File "/home/chichun/.local/lib/python3.6/site-packages/pandas/core/internals.py", line 3843, in get
  File "/home/chichun/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2527, in get_loc
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
